# Generated by Django 2.2.1 on 2019-05-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugname', models.CharField(max_length=256, verbose_name='标题')),
                ('bugtxt', models.TextField(verbose_name='内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='domain_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=100, verbose_name='域名')),
                ('id_del', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist', models.TextField(verbose_name='待办事项')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('poc_file', models.TextField(default='', null=True)),
                ('result', models.TextField()),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_fixed', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.TextField()),
                ('task_name', models.TextField()),
                ('status', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='toollist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.CharField(max_length=256, verbose_name='Tool_name')),
                ('tooltxt', models.TextField(verbose_name='detail')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='Issue_time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update_time')),
                ('is_del', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Req_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=5, verbose_name='METHOD')),
                ('host', models.CharField(max_length=40, verbose_name='HOST')),
                ('uri', models.CharField(default='/', max_length=100, verbose_name='FILE')),
                ('url', models.TextField(verbose_name='URL')),
                ('ua', models.TextField(verbose_name='User-agent')),
                ('referer', models.TextField(null=True, verbose_name='REFERER')),
                ('data', models.TextField(null=True, verbose_name='REQUEST BODY')),
                ('cookie', models.TextField(default='', verbose_name='COOKIE')),
            ],
            options={
                'unique_together': {('method', 'host', 'uri')},
            },
        ),
    ]
