# Generated by Django 2.2.1 on 2019-05-31 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_result_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toollist',
        ),
    ]
