# Generated by Django 2.2.1 on 2019-05-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_toollist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toollist',
        ),
    ]
