# Generated by Django 2.2.1 on 2019-05-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_toollist'),
    ]

    operations = [
        migrations.CreateModel(
            name='toollist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.CharField(max_length=256, verbose_name='Tool_name')),
                ('tooltxt', models.TextField(verbose_name='detail')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='Issue_time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update_time')),
                ('is_del', models.BooleanField(default=0)),
            ],
        ),
    ]
