# Generated by Django 2.2.1 on 2019-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_result_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_fixed', models.NullBooleanField(default=False)),
            ],
        ),
    ]
